In [1]:
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from time import time
from io import StringIO
import re

# load whole pdf as a text it will return string

In [2]:
def parse_pdf(filename):
    start_time = time()
    rsrcmgr = PDFResourceManager()
    rettxt = StringIO()
    laparams = LAParams()
    # 縦書き文字を横並びで出力する
    laparams.detect_vertical = True
    device = TextConverter(rsrcmgr, rettxt, codec='utf-8', laparams=laparams)
    # 処理するPDFを開く
    fp = open(filename, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)

    # maxpages：ページ指定（0は全ページ）
    for page in PDFPage.get_pages(fp, pagenos=None, maxpages=0, password=None,caching=True, check_extractable=True):
        interpreter.process_page(page)
    pdf_text = rettxt.getvalue() 
    fp.close()
    device.close()
    rettxt.close()
    print("load %s pdf cost %d time" % (filename, time()-start_time))
    return pdf_text

In [3]:
text = parse_pdf("CSR_REPORT.pdf")

load CSR_REPORT.pdf pdf cost 36 time

# if u want to load a table

In [13]:
import tabula

# Read pdf into DataFrame
df = tabula.read_pdf("test_pdf_table.pdf")

In [14]:
df

,2017/4/1,3125975140,962651001 233196279,Unnamed: 3,-0.6048689,-0.7229576,-0.5901115
0,2017/4/1,1.136063e+08,22345922 65042532,NaN,-0.664987,-0.721040,-0.641353
1,2017/4/1,1.000100e+10,4.1358E+10 1.8293E+10,NaN,1.836829,1.944885,2.468046
2,2017/4/1,3.126257e+09,94325 89862,NaN,-0.678786,-0.766883,-0.656217
3,2017/4/1,3.134825e+09,1871950252 2566659789,NaN,-0.493720,0.004395,-0.342108
4,2017/4/1,3.128807e+09,717241587 4076273818,NaN,0.307937,-0.027318,-0.024168
5,2017/4/1,3.117931e+09,140886478 1065861539,NaN,-0.402098,-0.077164,-0.346594
6,2017/4/1,3.128400e+09,6872527320 3.0021E+10,NaN,3.043400,2.907044,1.932812
7,2017/4/1,8.131492e+09,162542554 461031990,NaN,-0.612656,-0.731972,-0.616473
8,2017/4/1,1.000000e+10,122075626 1069489231,NaN,-0.430055,-0.627153,-0.547530
9,2017/4/1,8.136450e+09,1164109 1312878,NaN,-0.675021,-0.766619,-0.654643
10,2017/4/1,3.136438e+09,0 56890687,NaN,-0.654300,-0.765621,-0.650496
11,2017/4/1,3.123476e+09,941426152 6140644995,NaN,1.507064,0.218811,0.430006
12,2017/4/1,1.000100e+10,4946807888 3746691125,NaN,0.044321,0.048209,-0.175053
13,2017/4/1,1.000100e+10,5600294372 6385378783,NaN,-0.099612,0.968769,0.402833
14,2017/4/1,3.128801e+09,180096060 2387556766,NaN,-0.283538,-0.559976,-0.545568
15,2017/4/1,3.116365e+09,7138252503 4931355239,NaN,0.598076,0.593268,0.419727
16,2017/4/1,8.136912e+09,494900048 688433841,NaN,-0.607509,-0.723477,-0.592480
17,2017/4/1,3.116484e+09,6283465766 2.7343E+10,NaN,1.180027,0.906215,1.219923
18,2017/4/1,3.128981e+09,61510031 274605777,NaN,-0.510400,-0.628786,-0.570805
19,2017/4/1,8.134094e+09,2582224391 5453817685,NaN,0.712941,0.695141,0.222694
20,2017/4/1,3.114735e+09,15773 1493956,NaN,-0.678786,-0.766881,-0.656160
21,2017/4/1,3.121561e+09,4.079E+10 1.2147E+10,NaN,0.654289,0.711338,1.555082
22,2017/4/1,1.175556e+08,7304574 134719114,NaN,-0.665295,-0.742333,-0.642956
23,2017/4/1,1.000100e+10,5160896 462092187,NaN,-0.622198,-0.729934,-0.612469
24,2017/4/1,8.137530e+09,15917474 335805348,NaN,-0.365163,-0.637649,-0.615850
25,2017/4/1,3.135494e+09,2740738971 1038575952,NaN,0.044403,-0.593245,-0.323543
26,2017/4/1,1.000100e+10,20864046 1544502408,NaN,-0.421443,-0.654366,-0.491106
27,2017/4/1,3.120199e+09,2881136287 6258743481,NaN,0.173231,0.935463,0.089739
28,2017/4/1,3.119085e+09,2.1704E+10 8118233365,NaN,1.688984,1.554157,1.652060
29,2017/4/1,8.135398e+09,1.1186E+10 5955495817,NaN,0.738529,1.966843,1.003345
30,2017/4/1,8.136110e+09,0 0,NaN,-0.678796,-0.766891,-0.656227
31,2017/4/1,3.136383e+09,4474134465 7057144137,NaN,0.321677,1.217669,0.382302
32,2017/4/1,2.115095e+09,9343131499 6271235296,NaN,0.122445,-0.182269,0.123486
33,2017/4/1,8.133248e+09,11444076 187475848,NaN,-0.658437,-0.720778,-0.633329
34,2017/4/1,8.135618e+09,10692916 80838351,NaN,-0.654380,-0.707091,-0.631161
35,2017/4/1,3.119120e+09,801612484 2049857746,NaN,0.140232,-0.011346,-0.291237
36,2017/4/1,1.199569e+08,1.6317E+11 132016259,NaN,1.691338,1.439820,5.634741
37,2017/4/1,3.124811e+09,1182216798 705207725,NaN,-0.582492,-0.452189,-0.513120
38,2017/4/1,3.130747e+09,2.7411E+10 9606732784,NaN,1.298731,2.672221,1.472766
39,2017/4/1,3.119625e+09,103969324 2102738602,NaN,-0.461048,-0.228189,-0.428386
40,2017/4/1,1.339918e+08,0 0,NaN,-0.678771,-0.766052,-0.655865
41,2017/4/1,1.000200e+10,280749294 6651635,NaN,-0.674349,-0.714225,-0.623030
42,2017/4/1,8.136403e+09,351142144 7842949038,NaN,0.790784,-0.147271,0.250595
43,2017/4/1,3.129116e+09,108581177 2295721861,NaN,0.322748,-0.224866,-0.464100
44,2017/4/1,1.000100e+10,135740859 1367940190,NaN,-0.539762,-0.584654,-0.511880
45,2017/4/1,8.237631e+09,463 3828,NaN,-0.678796,-0.766891,-0.656227

In [12]:
print(df)

None